# Generated by Django 4.2 on 2024-01-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('origi', models.TextField()),
                ('dic', models.TextField()),
            ],
            options={
                'db_table': 'dict',
            },
        ),
    ]
